//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

@interface SBTodayTableHeaderView : UIView
{
    UILabel *_dateLabel;
    UILabel *_lunarDateLabel;
    _Bool _isContentValid;
    struct CGRect _calculatedDateLabelFrame;
    _Bool _achievedPreferredDateLabelLayout;
    struct CGSize _sizeThatFitsCalculatedDateLabelFrame;
    struct CGRect _calculatedLunarDateLabelFrame;
    long long _layoutMode;
}

+ (id)defaultBackgroundColor;
+ (id)defaultDateFontForMode:(long long)arg1;
+ (id)defaultLunarDateFont;
+ (id)defaultTextColor;
+ (double)lunarDateBaselineOffset;
- (_Bool)_dateLabelNeedsLayoutForSize:(struct CGSize)arg1;
- (double)_dateLabelWidthForSize:(struct CGSize)arg1 layoutMode:(long long)arg2;
- (_Bool)_isCachedSizeThatFitsValidForSize:(struct CGSize)arg1;
- (void)_layoutDateLabel;
- (void)_layoutLunarDateLabel;
- (struct CGRect)_lunarDateLabelFrameForBounds:(struct CGRect)arg1;
- (void)_updateForContentCategorySizeDidChange;
- (id)dateHeaderAttributedStringOnSingleLine:(_Bool)arg1;
- (id)dateHeaderOnSingleLine:(_Bool)arg1;
- (struct CGRect)dateLabelFrameForBounds:(struct CGRect)arg1 force:(_Bool)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)invalidateContent;
@property(nonatomic) long long layoutMode; // @synthesize layoutMode=_layoutMode;
- (void)layoutSubviews;
- (id)lunarCalendarIdentifier;
- (id)lunarDateHeaderString;
- (_Bool)showsLunarDate;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
@property(readonly, nonatomic) double visibleMinY;

@end

